spring:
  application:
    name: identity-service
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/identity}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  sms:
    provider:
      api-key: ${SMS_API_KEY:}
      api-hash: ${SMS_API_HASH:}
server:
  port: 8080